site_name: Rebrec's Sec Notes
site_description: 'Various notes from CTF experience'
site_author: 'rebrec'
site_url: 'https://rebrec.github.io/rebsecnotes/'
docs_dir: docs/
repo_name: 'rebrec/rebsecnotes'
repo_url: 'https://github.com/rebrec/rebsecnotes'
edit_uri: 'edit/main/docs/'
theme:
 name: 'material'
markdown_extensions:
 - codehilite:
     guess_lang: true
     use_pygments: true
plugins:
    - search
    - awesome-pages